image:
  file: .gitpod.Dockerfile
tasks:
  - name: Google Chrome
    command: >
      gp sync-await start &&
      gp await-port 5900 &&
      for i in `seq 10 -1 1` ; do echo -ne "\rStarting Chrome in $i " && sleep 1 && echo -ne "\r" ; done &&
      google-chrome --no-first-run --disable-dev-shm-usage --start-maximized https://github.com/gitpod-io/template-sveltekit
ports:
  - name: NoVNC
    port: 5900
    onOpen: open-preview
